###############################################################################
#
# Copyright 2006 - 2021, Paul Beckingham, Federico Hernandez.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# https://www.opensource.org/licenses/mit-license.php
#
###############################################################################

rule.precedence.color=deleted,completed,active,keyword.,tag.,project.,overdue,scheduled,due.today,due,blocked,blocking,recurring,uda.,tagged

# General decoration
color.label=
color.label.sort=
color.alternate=on gray2
color.header=color98
color.footnote=rgb013
color.warning=color172
color.error=color166
color.debug=rgb013

# Task state
color.completed=
color.deleted=
color.active=color234 on color78
color.recurring=rgb115
color.scheduled=on rgb012
color.until=
color.blocked=white on color237
color.blocking=white on color98

# Project
color.project.none=

# Priority
color.uda.priority.H=color172
color.uda.priority.L=color60
color.uda.priority.M=color220

# Tags
color.tag.next=color15
color.tag.none=
color.tagged=color246

# Due
color.due.today=color38 on black
color.due=color249
color.overdue=color166

# Report: burndown
color.burndown.done=on color38
color.burndown.pending=on color234
color.burndown.started=on color172

# Report: history
color.history.add=black on color78
color.history.done=black on color38
color.history.delete=black on color172

# Report: summary
color.summary.background=on color234
color.summary.bar=on color98

# Command: calendar
color.calendar.due.today=color0 on color38
color.calendar.due=color0 on color249
color.calendar.holiday=color255 on rgb013
color.calendar.overdue=color0 on color166
color.calendar.today=color0 on color78
color.calendar.weekend=on color235
color.calendar.weeknumber=rgb015

# Command: sync
color.sync.added=gray4
color.sync.changed=rgb015
color.sync.rejected=rgb004

# Command: undo
color.undo.after=rgb035
color.undo.before=rgb013
